"""empty message

Revision ID: 141933b9e0c6
Revises: 
Create Date: 2022-02-14 15:18:52.700828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141933b9e0c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_posts_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.drop_column('comments', 'content')
    op.drop_column('comments', 'posts_id')
    op.drop_column('comments', 'id')
    op.add_column('posts', sa.Column('date_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date_time')
    op.add_column('comments', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('comments', sa.Column('posts_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_posts_id_fkey', 'comments', 'comments', ['posts_id'], ['id'])
    op.drop_column('comments', 'post_id')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
