"""empty message

Revision ID: c51757b2b32c
Revises: 141933b9e0c6
Create Date: 2022-02-14 18:36:59.390628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51757b2b32c'
down_revision = '141933b9e0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('comment', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment')
    op.drop_column('comments', 'id')
    # ### end Alembic commands ###
